/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesempenhoRouteImport } from './routes/desempenho'
import { Route as MissoesRouteImport } from './routes/missoes'
import { Route as ProRouteImport } from './routes/pro'
import { Route as QuestoesRouteImport } from './routes/questoes'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as RevisarRouteImport } from './routes/revisar'
import { Route as LicaoLessonIdRouteImport } from './routes/licao.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesempenhoRoute = DesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => rootRouteImport,
} as any)
const MissoesRoute = MissoesRouteImport.update({
  id: '/missoes',
  path: '/missoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestoesRoute = QuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisarRoute = RevisarRouteImport.update({
  id: '/revisar',
  path: '/revisar',
  getParentRoute: () => rootRouteImport,
} as any)
const LicaoLessonIdRoute = LicaoLessonIdRouteImport.update({
  id: '/licao/$lessonId',
  path: '/licao/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/desempenho': typeof DesempenhoRoute
  '/missoes': typeof MissoesRoute
  '/pro': typeof ProRoute
  '/questoes': typeof QuestoesRoute
  '/ranking': typeof RankingRoute
  '/revisar': typeof RevisarRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desempenho': typeof DesempenhoRoute
  '/missoes': typeof MissoesRoute
  '/pro': typeof ProRoute
  '/questoes': typeof QuestoesRoute
  '/ranking': typeof RankingRoute
  '/revisar': typeof RevisarRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/desempenho': typeof DesempenhoRoute
  '/missoes': typeof MissoesRoute
  '/pro': typeof ProRoute
  '/questoes': typeof QuestoesRoute
  '/ranking': typeof RankingRoute
  '/revisar': typeof RevisarRoute
  '/licao/$lessonId': typeof LicaoLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/desempenho'
    | '/missoes'
    | '/pro'
    | '/questoes'
    | '/ranking'
    | '/revisar'
    | '/licao/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desempenho'
    | '/missoes'
    | '/pro'
    | '/questoes'
    | '/ranking'
    | '/revisar'
    | '/licao/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/desempenho'
    | '/missoes'
    | '/pro'
    | '/questoes'
    | '/ranking'
    | '/revisar'
    | '/licao/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesempenhoRoute: typeof DesempenhoRoute
  MissoesRoute: typeof MissoesRoute
  ProRoute: typeof ProRoute
  QuestoesRoute: typeof QuestoesRoute
  RankingRoute: typeof RankingRoute
  RevisarRoute: typeof RevisarRoute
  LicaoLessonIdRoute: typeof LicaoLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desempenho': {
      id: '/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof DesempenhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missoes': {
      id: '/missoes'
      path: '/missoes'
      fullPath: '/missoes'
      preLoaderRoute: typeof MissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questoes': {
      id: '/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof QuestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisar': {
      id: '/revisar'
      path: '/revisar'
      fullPath: '/revisar'
      preLoaderRoute: typeof RevisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licao/$lessonId': {
      id: '/licao/$lessonId'
      path: '/licao/$lessonId'
      fullPath: '/licao/$lessonId'
      preLoaderRoute: typeof LicaoLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesempenhoRoute: DesempenhoRoute,
  MissoesRoute: MissoesRoute,
  ProRoute: ProRoute,
  QuestoesRoute: QuestoesRoute,
  RankingRoute: RankingRoute,
  RevisarRoute: RevisarRoute,
  LicaoLessonIdRoute: LicaoLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
